kind: ConfigMap
apiVersion: v1
metadata:
  name: configmap-wp
  namespace: wp-micro
data:
  WORDPRESS_DB_HOST: wp-db-service.wp-micro.svc.cluster.local
  WORDPRESS_DB_NAME: yavuz
  WORDPRESS_DB_USER: admin

--- 

kind: ConfigMap
apiVersion: v1
metadata:
  name: configmap-msql
  namespace: wp-micro
data:
  MYSQL_DATABASE: yavuz
  MYSQL_USER: admin

