apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wp-micro
  name: wp-deployment
  labels:
    app: wp-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wp-app
  # strategy:
  #   type: RollingUpdate 
  #   # rollingUpdate:
  #   #   maxUnavailable: 2
  #   #   maxSurge: 1 
  template:
    metadata:
      labels:
        app: wp-app
    spec:
      containers:
      - name: wp-app
        image: wordpress
        ports:
          - containerPort: 80
        envFrom:
          - secretRef:
              name: wp-secret-worpress
          - configMapRef:
              name: configmap-wp
        volumeMounts:
          - name: wp-pv-wordpress
            mountPath: /var/www/html
      volumes:
        - name: wp-pv-wordpress
          persistentVolumeClaim:
            claimName: wp-pv-wordpress

---
apiVersion: v1
kind: Service
metadata:
  namespace: wp-micro
  name: wp-service
spec:
  type: NodePort
  selector:
    app: wp-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001

--- 

apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: wp-micro
  name: wp-pv-wordpress
  labels:
    app: wordpress
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /mnt/data
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: wp-micro
  name: wordpress-pvc
spec:
  selector:
    matchLabels:
      app: wordpress
  storageClassName: manual
  resources:
    requests:
      storage: 3Gi
  # volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce



